get http://localhost:8080/api/words

###

post http://localhost:8080/api/words
Content-Type: application/json

{
  "english_word": "car",
  "finnish_word": "auto",
  "learning_direction": "eng"
}

###

delete http://localhost:8080/api/words/1

###

patch http://localhost:8080/api/words/65
content-type: application/json

{"english_word": "car", "finnish_word": "auto"}
