get http://localhost:8080/api/words

###

post http://localhost:8080/api/words
Content-Type: application/json

{
  "english_word": "car",
  "finnish_word": "auto",
  "learning_direction": "english_to_finnish"
}

###

delete http://localhost:8080/api/words/4

###

patch http://localhost:8080/api/words/1
content-type: application/json

{"english_word": "cat", "finnish_word": "kissa"}
